<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-K0J5U40" failures="2" tests="2" name="Test2" time="24.214" errors="0" timestamp="23 Jul 2020 10:37:31 GMT">
  <testcase classname="resources.ShoppingCartTest" name="shop" time="14.282">
    <failure type="java.lang.AssertionError" message="expected [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING] but found [123]">
      <![CDATA[java.lang.AssertionError: expected [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING] but found [123]
	at resources.ShoppingCartTest.shop(ShoppingCartTest.java:63)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- shop -->
  <testcase classname="resources.getGoogleTest" name="getURL" time="1.138">
    <failure type="java.lang.AssertionError" message="expected [Google123] but found [Google]">
      <![CDATA[java.lang.AssertionError: expected [Google123] but found [Google]
	at resources.getGoogleTest.getURL(getGoogleTest.java:27)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- getURL -->
</testsuite> <!-- Test2 -->
